        <p>
            <table>
                <tr>
                    <td>$title</td>
                </tr>
                <tr>
                    <td>$image</td>
                </tr>
$legend
            </table>
        </p>
